---

- name: ensure containers are removed
  docker_container:
    name: "{{ item.name }}"
    state: "absent"
  with_items: "{{ refstack_services[::-1] }}"
  vars:
    handler: delete service {{ item.name }}
  notify: "{{ handler if handler in refstack_handlers else 'default handler' }}"

- name: ensure volumes are removed
  docker_volume:
    name: "{{ item.name }}"
    state: "absent"
  with_items: "{{ refstack_volumes[::-1] }}"
  vars:
    handler: delete volume {{ item.name }}
  notify: "{{ handler if handler in refstack_handlers else 'default handler' }}"
