---
- name: create a volumes
  docker_volume:
    name: "{{ item.name }}"
  with_items: "{{ refstack_volumes }}"
  vars:
    handler: create volume {{ item.name }}
  notify: "{{ handler if handler in refstack_handlers else 'default handler' }}"

- name: create services
  docker_container: "{{ item | combine(present) }}"
  with_items: "{{ refstack_services }}"
  vars:
    present:
      state: present
    handler: create service {{ item.name }}
  notify: "{{ handler if handler in refstack_handlers else 'default handler' }}"

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: start services
  docker_container: "{{ item | combine(started) }}"
  with_items: "{{ refstack_services }}"
  vars:
    started:
      state: started
    handler: start service {{ item.name }}
  notify: "{{ handler if handler in refstack_handlers else 'default handler' }}"
